### PR TITLE
Simple blacklist for item usage

### LINKED ISSUE #144: CR gets stuck trying to use an item and fails
Sometimes http://www.wowhead.com/item=132510 will go onto cooldown but the UI won't show it. It may even return that it's off cooldown if you use GetItemCooldown (not sure) but it fails to cast because it's on CD.

The CR locks up when this happens.

### PR DESCRIPTION
**Pull request by vorus**
Attempt to resolve #144.

@Yobleed is having issues with item usage.  ```GetItemCooldown``` is returning ```0, 0, 1``` after item has been used.

The following will implement a blacklist to prevent items be used more than once every 5 seconds.

Input would be appreciated on the amount of time, as well as if any items is actually used more frequently than every 5 seconds.

### CODE REVIEW

File: system/actions.lua [hunk 1]
```diff
@@ -84,14 +85,31 @@ NeP.Actions['pause'] = function(eval)
...
 -- Items
 NeP.Actions['#'] = function(eval)
 	local item = eval[1]
 	if item and item.id and GetItemSpell(item.spell) then
-		return IsUsableItem(item.spell)
+		if IsUsableItem(item.spell)
 		and select(2,GetItemCooldown(item.id)) == 0
 		and GetItemCount(item.spell) > 0
-		and NeP.Helpers:Check(item.spell, eval.target)
+		and NeP.Helpers:Check(item.spell, eval.target) then
```
Comment (MrTheSoulz) [inline system/actions.lua]: https://github.com/MrTheSoulz/NerdPack/blob/master/system/helpers.lua#L32
Blacklists the item, then  NeP.Helpers:Check(item.spell, eval.target) should return false.

Comment (vorus) [inline system/actions.lua]: @Yobleed was stating the error message "Item is not ready" does not show for him btw

Comment (Yobleed) [inline system/actions.lua]: so can it be merged?
